.build_common:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

.build_basic:
  extends: .build_common
  script:
    - mkdir build
    - cd build
    - CC=${CC} CXX=${CXX} cmake ../ -DCMAKE_PREFIX_PATH=${PREFIX_PATH} -G Ninja
    - ninja

.build_linux:
  extends: .build_basic
  variables:
    PREFIX_PATH: /home/falco/Qt/6.0.2/gcc_64

build ubuntu20-gcc10:
  extends: .build_linux
  tags:
    - linux
  variables:
    CC: gcc
    CXX: g++

build ubuntu20-clang11:
  extends: .build_linux
  tags:
    - linux, clang
  variables:
     CC: clang
     CXX: clang++

build win10-vs2019:
  extends: .build_basic
  tags:
    - visual-studio, win10
  variables:   
    CC: cl
    CXX: cl
    PREFIX_PATH: C:/Qt/6.0.2/msvc2019_64

build win10-cygwin-gcc10:
  extends: .build_basic
  tags:
    - gcc, win10
  variables:
    CC: gcc
    CXX: g++
    PREFIX_PATH: C:/Qt/6.0.2/mingw81_64

build macos-gcc10:
  extends: .build_basic
  tags:
    - macos, gcc
  variables:
    CC: gcc-10
    CXX: g++-10
    PREFIX_PATH: /Users/falcogirgis/Qt/6.0.2/clang_64

build android:
  extends: .build_common
  tags:
    - android
  variables: 
    CMAKE_TOOLCHAIN: /home/falco/Android/Sdk/ndk/21.3.6528147/build/cmake/android.toolchain.cmake
  script:
    - mkdir build
    - cd build
    - echo ${CMAKE_TOOLCHAIN}
    - cmake ../ -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} -G Ninja
    - ninja
    
    
build ios:
  extends: .build_common
  tags: 
    - ios
  variables:
    CMAKE_TOOLCHAIN: ../build-environment/toolchains/ios-cmake/ios.toolchain.cmake
  script:
    - mkdir build
    - cd build
    - cmake ../ -G Xcode -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} -DPLATFORM=OS64
    - cmake --build . 

build dreamcast:
  extends: .build_common
  tags:
    - dc
  variables:
    CC: sh-elf-gcc
    CXX: sh-elf-g++
    CMAKE_TOOLCHAIN: ../build-environment/toolchains/dreamcast.toolchain.cmake
  script:
    - /home/falco/Documents/dev/docker-kallistios-sdk/dcbuild.sh bash
    - mkdir build
    - cd build
    - CC=${CC} CXX=${CXX} cmake ../ -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN} 
    - make

build psp:
  extends: .build_common
  tags:
    - psp
  variables:
    PSP_SDK: /usr/local/pspdev/bin
  script:
    - mkdir build
    - cd build
    - ${PSP_SDK}/psp-cmake ../
    - make

build web:
  extends: .build_common
  tags:
    - webasm
  variables:
    ENV_SCRIPT: /home/falco/Documents/dev/emsdk/emsdk_env.sh
  script:
    - source ${ENV_SCRIPT}
    - mkdir build
    - cd build
    - emcmake cmake ..
    - emmake make
