include:
  - remote: https://raw.githubusercontent.com/gyrovorbis/libgimbal/master/util/pipeline-template.yml

variables:
  BINARY_PATH: test
  BINARY_NAME: ElysianVmuTests
  PROJECT_CMAKE_ARGS: -DEVMU_ENABLE_TESTS=ON -DGYRO_PLATFORM=GYRO_PLATFORM_Qt
  BUILD_WIN_MSVC_DISABLED: true
  BUILD_DREAMCAST_DISABLED: true
  BUILD_ANDROID_SIM_DISABLED: true
  BUILD_IOS_SIM_DISABLED: true
  BUILD_PSVITA_DISABLED: true
  BUILD_WEBASM_DISABLED: true 