include:
  - remote: https://raw.githubusercontent.com/gyrovorbis/libgimbal/master/util/pipeline-template.yml

variables:
  BINARY_PATH: test
  BINARY_NAME: ElysianVmuTests
  PROJECT_CMAKE_ARGS: -DEVMU_ENABLE_TESTS=ON